# Stubs for flask_easyjwt (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .flask_easyjwt import FlaskEasyJWT as FlaskEasyJWT
from easyjwt import Algorithm as Algorithm, CreationError as CreationError, EasyJWTError as EasyJWTError, ExpiredTokenError as ExpiredTokenError, ImmatureTokenError as ImmatureTokenError, IncompatibleKeyError as IncompatibleKeyError, InvalidAudienceError as InvalidAudienceError, InvalidClaimSetError as InvalidClaimSetError, InvalidClassError as InvalidClassError, InvalidIssuedAtError as InvalidIssuedAtError, InvalidIssuerError as InvalidIssuerError, InvalidSignatureError as InvalidSignatureError, MissingRequiredClaimsError as MissingRequiredClaimsError, UnspecifiedClassError as UnspecifiedClassError, UnsupportedAlgorithmError as UnsupportedAlgorithmError, VerificationError as VerificationError
