# Stubs for flask_easyjwt.flask_easyjwt (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from datetime import datetime
from easyjwt import EasyJWT
from typing import Any, Iterable, Optional, Type, TypeVar, Union

FlaskEasyJWTClass = TypeVar('FlaskEasyJWTClass', bound='FlaskEasyJWT', covariant=True)

class FlaskEasyJWT(EasyJWT):
    expiration_date: Any
    def __init__(self, key: Optional[str]=...) -> None: ...
    def create(self, issued_at: Optional[datetime]=...) -> str: ...
    @classmethod
    def verify(cls: Type[FlaskEasyJWTClass], token: str, key: Optional[str]=..., issuer: Optional[str]=..., audience: Optional[Union[Iterable[str], str]]=...) -> FlaskEasyJWTClass: ...
